apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "logger": {
        "formatter": {{ .Values.logger.formatter | quote }},
        "requestHeaders": {
          "traceIDHeaderName": {{ .Values.logger.requestHeaders.traceIDHeaderName | quote }}
        }
      }
    }